import {Dimensions, StyleSheet} from 'react-native';
import {COLORS} from '@/themes';

const height = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    minHeight: height,
    padding: 16,
    backgroundColor: COLORS.BACKGROUND,
  },
  header: {
    paddingTop: 32,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  pageTitle: {
    fontFamily: 'Mulish-Bold',
    fontSize: 18,
    color: COLORS.WHITE,
    marginLeft: 4,
  },
  redirectBtnToSetPasscodePage: {
    height: 48,
    backgroundColor: COLORS.BG_GRAY_2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    paddingHorizontal: 12,
  },
  setPasscodeTxt: {
    fontFamily: 'Mulish-SemiBold',
    fontSize: 16,
    color: COLORS.WHITE,
    marginLeft: 8,
  },
  shortSetPasscodeTxt: {
    fontFamily: 'Mulish-Medium',
    fontSize: 16,
    color: COLORS.WHITE,
  },
  updateButton: {
    height: 48,
    borderRadius: 12,
    backgroundColor: COLORS.BG_GRAY_2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
  },
  updateBtnTxt: {
    color: COLORS.WHITE,
    fontFamily: 'Mulish-SemiBold',
    fontSize: 16,
    color: COLORS.WHITE,
  },
  buttonStyle: {
    height: 48,
    backgroundColor: COLORS.WARNING,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 32,
    left: 16,
    right: 16,
  },
  buttonTxtStyle: {
    fontFamily: 'Mulish-SemiBold',
    fontSize: 16,
    color: COLORS.SECONDARY,
  },
  OTPContainerStyles: {
    marginTop: 100,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  OTPInputStyles: {
    width: 52,
    height: 62,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: COLORS.TEXT_INPUT_BORDER,
    backgroundColor: COLORS.WARNING,
    fontFamily: 'Mulish-Bold',
    fontSize: 24,
    color: COLORS.LOGIN_BUTTON,
    textAlign: 'center',
    marginLeft: 12,
    marginRight: 12,
  },
  modal: {
    backgroundColor: COLORS.BG_MODAL,
    borderRadius: 40,
    paddingTop: 32,
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 40,
    alignItems: 'center',
  },
  modalTitle: {
    marginTop: 24,
    marginBottom: 8,
    fontFamily: 'Mulish-SemiBold',
    fontSize: 20,
    color: COLORS.WHITE,
  },
  modalDesc: {
    fontFamily: 'Mulish-Regular',
    fontSize: 14,
    color: COLORS.LIGHT,
    maxWidth: 280,
    textAlign: 'center',
    marginBottom: 40,
  },
  modalButton: {
    width: '100%',
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    flexShrink: 0,
    backgroundColor: COLORS.WARNING,
  },
  modalButtonTxt: {
    fontFamily: 'Mulish-SemiBold',
    color: COLORS.SECONDARY,
    fontSize: 16,
  },
});
